<?php if ( ! defined( 'ABSPATH' ) ) { exit; } ?>
<div class="wrap os-wrap" id="os-settings-page">
    <h1 class="os-page-title">
        <span class="dashicons dashicons-admin-settings"></span>
        <?php esc_html_e( 'Olama Stores Settings', 'olama-stores' ); ?>
    </h1>
    <div class="nav-tab-wrapper">
        <a href="#tab-general"    class="nav-tab nav-tab-active" data-tab="general"><?php esc_html_e( 'General', 'olama-stores' ); ?></a>
        <a href="#tab-warehouses" class="nav-tab" data-tab="warehouses"><?php esc_html_e( 'Warehouses', 'olama-stores' ); ?></a>
        <a href="#tab-categories" class="nav-tab" data-tab="categories"><?php esc_html_e( 'Categories', 'olama-stores' ); ?></a>
        <a href="#tab-units" class="nav-tab" data-tab="units"><?php esc_html_e( 'Units', 'olama-stores' ); ?></a>
        <a href="#tab-providers" class="nav-tab" data-tab="providers"><?php esc_html_e( 'Providers', 'olama-stores' ); ?></a>
        <a href="#tab-custom-models" class="nav-tab" data-tab="custom-models"><?php esc_html_e( 'Custom Models', 'olama-stores' ); ?></a>
        <a href="#tab-fabrics" class="nav-tab" data-tab="fabrics"><?php esc_html_e( 'Fabrics', 'olama-stores' ); ?></a>
        <a href="#tab-colors" class="nav-tab" data-tab="colors"><?php esc_html_e( 'Colors', 'olama-stores' ); ?></a>
        <a href="#tab-sizes" class="nav-tab" data-tab="sizes"><?php esc_html_e( 'Sizes', 'olama-stores' ); ?></a>
        <a href="#tab-entitlements" class="nav-tab" data-tab="entitlements"><?php esc_html_e( 'Uniform Entitlements', 'olama-stores' ); ?></a>
        <a href="#tab-integration" class="nav-tab" data-tab="integration"><?php esc_html_e( 'School Integration', 'olama-stores' ); ?></a>
        <a href="#tab-maintenance" class="nav-tab" data-tab="maintenance"><?php esc_html_e( 'Maintenance', 'olama-stores' ); ?></a>
    </div>

    <!-- General Tab -->
    <div id="tab-general" class="os-tab-content">
        <form method="post" action="options.php">
            <?php settings_fields( 'os_settings' ); ?>
            <table class="form-table">
                <tr>
                    <th><?php esc_html_e( 'SKU Prefix', 'olama-stores' ); ?></th>
                    <td><input type="text" name="os_sku_prefix" value="<?php echo esc_attr( get_option( 'os_sku_prefix', 'SKU' ) ); ?>"></td>
                </tr>
                <tr>
                    <th><?php esc_html_e( 'Low Stock Email Alerts', 'olama-stores' ); ?></th>
                    <td><label><input type="checkbox" name="os_low_stock_email" value="1" <?php checked( get_option( 'os_low_stock_email' ), '1' ); ?>> <?php esc_html_e( 'Send daily email when items fall below minimum stock', 'olama-stores' ); ?></label></td>
                </tr>
                <tr>
                    <th><?php esc_html_e( 'Custom Estimation Results Are Editable', 'olama-stores' ); ?></th>
                    <td><label><input type="checkbox" name="os_custom_estimation_editable" value="1" <?php checked( get_option( 'os_custom_estimation_editable' ), '1' ); ?>> <?php esc_html_e( 'Allow manual adjustment of quantities generated by the Custom Estimation engine.', 'olama-stores' ); ?></label></td>
                </tr>
            </table>
            <?php submit_button(); ?>
        </form>

        <div class="os-card os-card-danger" style="margin-top: 30px; max-width: 600px; border: 1px solid var(--os-border); background: var(--os-surface); padding: 24px; box-shadow: var(--os-shadow-sm); border-radius: var(--os-radius); position: relative; overflow: hidden; transition: all 0.3s ease;">
            <div style="position: absolute; top: 0; left: 0; width: 4px; height: 100%; background: var(--os-danger);"></div>
            <h3 style="color: var(--os-danger); margin-top: 0; display: flex; align-items: center; gap: 8px; font-weight: 700; font-size: 1.15rem;">
                <span class="dashicons dashicons-warning" style="color: var(--os-danger); font-size: 1.3rem; width: 1.3rem; height: 1.3rem;"></span>
                <?php esc_html_e( 'Clear Warehouse', 'olama-stores' ); ?>
            </h3>
            <p style="margin: 12px 0; line-height: 1.5; color: var(--os-text-muted); font-size: 0.9rem;">
                <?php esc_html_e( 'Permanently delete all Olama store transactions completely. This action will delete stock movements, custody assignments, returns, transfers, and inventory counts. All item stock levels will be reset to zero.', 'olama-stores' ); ?>
            </p>
            <p style="margin: 0 0 16px 0; font-weight: 600; color: var(--os-danger); font-size: 0.85rem; display: flex; align-items: center; gap: 6px;">
                <span class="dashicons dashicons-shield-alt" style="font-size: 1rem; width: 1rem; height: 1rem;"></span>
                <?php esc_html_e( 'Setting details and the items list will be completely kept.', 'olama-stores' ); ?>
            </p>
            <button type="button" class="button" id="os-btn-clear-warehouse" style="background: var(--os-danger); color: #fff; border-color: var(--os-danger); font-weight: 600; padding: 6px 16px; height: auto; font-size: 0.875rem; border-radius: 6px; cursor: pointer; transition: background-color 0.2s ease;">
                <?php esc_html_e( 'Clear Warehouse', 'olama-stores' ); ?>
            </button>
        </div>

        <!-- REC-14: Year-End Transition Panel -->
        <?php if ( OS_Roles::can( 'os_manage_settings' ) ) : ?>
        <div class="os-card" style="margin-top:20px; max-width:700px; border:1px solid var(--os-border); background:var(--os-surface); padding:24px; border-radius:var(--os-radius); box-shadow:var(--os-shadow-sm); position:relative; overflow:hidden;">
            <div style="position:absolute; top:0; left:0; width:4px; height:100%; background:#7c3aed;"></div>
            <h3 style="margin-top:0; display:flex; align-items:center; gap:8px; color:#5b21b6;">
                <span class="dashicons dashicons-calendar-alt" style="font-size:1.3rem; width:1.3rem; height:1.3rem; color:#7c3aed;"></span>
                <?php esc_html_e( 'Year-End Transition', 'olama-stores' ); ?>
            </h3>
            <p style="color:var(--os-text-muted); margin:8px 0 16px;">
                <?php esc_html_e( 'Run these tasks before activating a new academic year. Load the summary first to understand the current state.', 'olama-stores' ); ?>
            </p>

            <div id="os-year-transition-summary" style="background:var(--os-bg,#f0f0f1); border-radius:6px; padding:16px; margin-bottom:16px;">
                <p style="margin:0; color:#666;"><?php esc_html_e( 'Click the button below to load the year-end summary.', 'olama-stores' ); ?></p>
            </div>

            <div style="display:flex; gap:8px; flex-wrap:wrap;">
                <button type="button" class="button" id="os-yt-load-summary">
                    <span class="dashicons dashicons-search" style="margin-top:3px;"></span>
                    <?php esc_html_e( 'Load Summary', 'olama-stores' ); ?>
                </button>
                <button type="button" class="button" id="os-yt-export-balances">
                    <span class="dashicons dashicons-download" style="margin-top:3px;"></span>
                    <?php esc_html_e( 'Export Stock Balances', 'olama-stores' ); ?>
                </button>
                <button type="button" class="button" id="os-yt-flag-overdue" style="color:#7c3aed; border-color:#7c3aed;">
                    <span class="dashicons dashicons-flag" style="margin-top:3px;"></span>
                    <?php esc_html_e( 'Flag Overdue Custody', 'olama-stores' ); ?>
                </button>
            </div>
        </div>
        <?php endif; ?>

        <?php
        ?>
    </div>

    <!-- Warehouses Tab -->
    <div id="tab-warehouses" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Warehouses', 'olama-stores' ); ?></h2>
        <button type="button" class="button button-primary" id="os-btn-add-warehouse"><?php esc_html_e( '+ Add Warehouse', 'olama-stores' ); ?></button>
        <div id="os-warehouses-list" style="margin-top:16px;">
            <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
        </div>

        <div id="os-warehouse-modal" class="os-modal" style="display:none;">
            <div class="os-modal-content">
                <h2 id="os-wh-modal-title"><?php esc_html_e( 'Add Warehouse', 'olama-stores' ); ?></h2>
                <input type="hidden" id="os-wh-id" value="">
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Name', 'olama-stores' ); ?></label>
                    <input type="text" id="os-wh-name">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Arabic Name', 'olama-stores' ); ?></label>
                    <input type="text" id="os-wh-name-ar" dir="rtl">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Location', 'olama-stores' ); ?></label>
                    <input type="text" id="os-wh-location">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Warehouse Type', 'olama-stores' ); ?></label>
                    <select id="os-wh-type">
                        <option value="items"><?php esc_html_e( 'General Items', 'olama-stores' ); ?></option>
                        <option value="custom"><?php esc_html_e( 'School Custom', 'olama-stores' ); ?></option>
                        <option value="books"><?php esc_html_e( 'Books', 'olama-stores' ); ?></option>
                    </select>
                </div>
                <div class="os-form-actions">
                    <button type="button" class="button button-primary" id="os-wh-save"><?php esc_html_e( 'Save', 'olama-stores' ); ?></button>
                    <button type="button" class="button os-modal-close"><?php esc_html_e( 'Cancel', 'olama-stores' ); ?></button>
                </div>
            </div>
        </div>
    </div>

    <!-- Categories Tab (Global) -->
    <div id="tab-categories" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Categories', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Unified categories used for both Inventory and Academic Evaluations.', 'olama-stores' ); ?></p>
        <div id="os-categories-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-cat-name" placeholder="<?php esc_attr_e('Category Name', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-cat"><?php esc_html_e('Add Category', 'olama-stores');?></button>
            </div>
            <div id="os-categories-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>

    <!-- Units Tab (Global) -->
    <div id="tab-units" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Units', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Unified units used for both Measurement and Curriculum Units.', 'olama-stores' ); ?></p>
        <div id="os-units-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-unit-name" placeholder="<?php esc_attr_e('Unit Name (e.g. Piece)', 'olama-stores');?>" style="flex: 2;">
                <input type="text" id="os-new-unit-symbol" placeholder="<?php esc_attr_e('Symbol (e.g. pc)', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-unit"><?php esc_html_e('Add Unit', 'olama-stores');?></button>
            </div>
            <div id="os-units-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>

    <!-- Providers Tab -->
    <div id="tab-providers" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Providers', 'olama-stores' ); ?></h2>
        <button type="button" class="button button-primary" id="os-btn-add-provider"><?php esc_html_e( '+ Add Provider', 'olama-stores' ); ?></button>
        <div id="os-providers-list" style="margin-top:16px;">
            <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
        </div>

        <div id="os-provider-modal" class="os-modal" style="display:none;">
            <div class="os-modal-content">
                <h2 id="os-provider-modal-title"><?php esc_html_e( 'Add Provider', 'olama-stores' ); ?></h2>
                <input type="hidden" id="os-provider-id" value="">
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Company Name', 'olama-stores' ); ?> *</label>
                    <input type="text" id="os-provider-name" required>
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Mobile Contact', 'olama-stores' ); ?></label>
                    <input type="text" id="os-provider-mobile">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Location', 'olama-stores' ); ?></label>
                    <input type="text" id="os-provider-location">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Contact Person', 'olama-stores' ); ?></label>
                    <input type="text" id="os-provider-person">
                </div>
                <div class="os-form-row">
                    <label><?php esc_html_e( 'Active Status', 'olama-stores' ); ?></label>
                    <label style="display: flex; align-items: center; gap: 8px;">
                        <input type="checkbox" id="os-provider-active" style="width: auto !important; height: auto !important; margin: 0 !important;"> 
                        <span><?php esc_html_e( 'Active Provider (Used for cost calculations)', 'olama-stores' ); ?></span>
                    </label>
                </div>
                <div class="os-form-actions">
                    <button type="button" class="button button-primary" id="os-provider-save"><?php esc_html_e( 'Save', 'olama-stores' ); ?></button>
                    <button type="button" class="button os-modal-close"><?php esc_html_e( 'Cancel', 'olama-stores' ); ?></button>
                </div>
            </div>
        </div>
    </div>

    <!-- Uniform Entitlements Tab -->
    <div id="tab-entitlements" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Uniform Entitlements', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Define the quantities of uniform custom models that students in each grade are entitled to receive per academic year.', 'olama-stores' ); ?></p>
        
        <div class="os-card" style="margin-bottom: 20px; padding: 20px; border: 1px solid var(--os-border); background: var(--os-surface); border-radius: var(--os-radius); max-width: 800px;">
            <div style="display: flex; gap: 15px; flex-wrap: wrap; align-items: flex-end;">
                <div style="flex: 1; min-width: 150px;">
                    <label style="display:block; margin-bottom: 5px; font-weight:600;"><?php esc_html_e( 'Grade', 'olama-stores' ); ?> *</label>
                    <select id="os-ent-grade" style="width:100%; height: 35px;"></select>
                </div>
                <div style="flex: 1; min-width: 150px;">
                    <label style="display:block; margin-bottom: 5px; font-weight:600;"><?php esc_html_e( 'Uniform Model', 'olama-stores' ); ?> *</label>
                    <select id="os-ent-model" style="width:100%; height: 35px;"></select>
                </div>
                <div style="width: 100px;">
                    <label style="display:block; margin-bottom: 5px; font-weight:600;"><?php esc_html_e( 'Quantity', 'olama-stores' ); ?> *</label>
                    <input type="number" id="os-ent-qty" min="1" value="1" style="width:100%; height: 35px;">
                </div>
                <div>
                    <button type="button" class="button button-primary" id="os-btn-add-entitlement" style="height: 35px; font-weight:600;"><?php esc_html_e( 'Add Entitlement', 'olama-stores' ); ?></button>
                </div>
            </div>
        </div>

        <div id="os-entitlements-list" style="max-width: 800px;">
            <span class="os-loading"><?php esc_html_e( 'Loading entitlements…', 'olama-stores' ); ?></span>
        </div>
    </div>

    <!-- Integration Tab -->
    <div id="tab-integration" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Olama Core Integration', 'olama-stores' ); ?></h2>
        <?php if ( OS_School_Integration::is_core_available() ): ?>
            <div class="notice notice-success inline"><p>
                <strong><?php esc_html_e( 'Connected', 'olama-stores' ); ?></strong>
                — <?php printf( esc_html__( 'Olama Core %s is the active people and academic data source.', 'olama-stores' ), esc_html( OLAMA_CORE_VERSION ) ); ?>
            </p></div>
            <table class="form-table">
                <tr>
                    <th><?php esc_html_e( 'Active Academic Year', 'olama-stores' ); ?></th>
                    <td><strong><?php echo esc_html( os_get_active_year_name() ); ?></strong>
                        (ID: <?php echo esc_html( os_get_active_year_id() ); ?>)
                        <br><small><?php esc_html_e( 'Olama Stores uses this year ID as the default academic_year_id for all new records.', 'olama-stores' ); ?></small>
                    </td>
                </tr>
                <tr>
                    <th><?php esc_html_e( 'Employee Source', 'olama-stores' ); ?></th>
                    <td><?php esc_html_e( 'Olama Core employees table — synchronized employee profiles and employee numbers.', 'olama-stores' ); ?></td>
                </tr>
                <tr>
                    <th><?php esc_html_e( 'Student Source', 'olama-stores' ); ?></th>
                    <td><?php
                        $count = count( OS_School_Integration::get_students( array( 'academic_year_id' => os_get_active_year_id() ) ) );
                        printf( esc_html__( 'Olama Core students and student-year tables — %d students in the current snapshot.', 'olama-stores' ), $count );
                    ?></td>
                </tr>
            </table>
        <?php else: ?>
            <div class="notice notice-warning inline"><p>
                <?php esc_html_e( 'Olama Core is not active. Stores will use legacy school data when available.', 'olama-stores' ); ?>
            </p></div>
        <?php endif; ?>
    </div>

    <!-- Maintenance Tab -->
    <div id="tab-maintenance" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Maintenance & Testing', 'olama-stores' ); ?></h2>
        <div class="card" style="max-width: 600px; border: 1px solid #ccd0d4; background: #fff; padding: 20px; box-shadow: 0 1px 1px rgba(0,0,0,.04); margin-top: 20px; border-radius: var(--os-radius);">
            <h3 style="color: #d63638; margin-top: 0; display: flex; align-items: center; gap: 8px;">
                <span class="dashicons dashicons-warning" style="color: #d63638;"></span>
                <?php esc_html_e( 'Reset Store Data (Testing Only)', 'olama-stores' ); ?>
            </h3>
            <p><?php esc_html_e( 'This action is destructive and cannot be undone. It will:', 'olama-stores' ); ?></p>
            <ul style="list-style-type: disc; margin-left: 20px; margin-bottom: 20px;">
                <li><?php esc_html_e( 'Delete all transaction data, including: stock movements, employee custody, student withdrawals, books withdrawals, and transfers.', 'olama-stores' ); ?></li>
                <li><?php esc_html_e( 'Zero the balance (On Hand & Reserved) of all items across all warehouses.', 'olama-stores' ); ?></li>
                <li><?php esc_html_e( 'Clear the audit log history.', 'olama-stores' ); ?></li>
            </ul>
            <p style="font-weight: bold; color: #d63638; margin-bottom: 20px;">
                <?php esc_html_e( 'Please proceed with caution. This feature is intended for development and testing environments only.', 'olama-stores' ); ?>
            </p>
            <div>
                <button type="button" class="button" id="os-btn-reset-store-data" style="background: #d63638; color: #fff; border-color: #d63638; padding: 5px 15px; height: auto; text-decoration: none; font-weight: 600;">
                    <?php esc_html_e( 'Delete All Transactions & Zero Balances', 'olama-stores' ); ?>
                </button>
            </div>
        </div>
    </div>


    <!-- Custom Models Tab -->
    <div id="tab-custom-models" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Custom Models', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Manage custom models that can be assigned to school items.', 'olama-stores' ); ?></p>
        <div id="os-custom-models-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-model-name" placeholder="<?php esc_attr_e('Model Name', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-model"><?php esc_html_e('Add Model', 'olama-stores');?></button>
            </div>
            <div id="os-custom-models-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>

    <!-- Fabrics Tab -->
    <div id="tab-fabrics" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Fabrics', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Manage fabric types that can be assigned to school items.', 'olama-stores' ); ?></p>
        <div id="os-fabrics-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-fabric-name" placeholder="<?php esc_attr_e('Fabric Name', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-fabric"><?php esc_html_e('Add Fabric', 'olama-stores');?></button>
            </div>
            <div id="os-fabrics-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>

    <!-- Colors Tab -->
    <div id="tab-colors" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Colors', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Manage colors that can be assigned to school items.', 'olama-stores' ); ?></p>
        <div id="os-colors-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-color-name" placeholder="<?php esc_attr_e('Color Name', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-color"><?php esc_html_e('Add Color', 'olama-stores');?></button>
            </div>
            <div id="os-colors-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>

    <!-- Sizes Tab -->
    <div id="tab-sizes" class="os-tab-content" style="display:none;">
        <h2><?php esc_html_e( 'Sizes', 'olama-stores' ); ?></h2>
        <p class="description"><?php esc_html_e( 'Manage sizes that can be assigned to school items.', 'olama-stores' ); ?></p>
        <div id="os-sizes-manager">
            <div style="display: flex; gap: 10px; margin-bottom: 20px;">
                <input type="text" id="os-new-size-name" placeholder="<?php esc_attr_e('Size Name/Number', 'olama-stores');?>" style="flex: 1;">
                <button type="button" class="button button-primary" id="os-btn-add-size"><?php esc_html_e('Add Size', 'olama-stores');?></button>
            </div>
            <div id="os-sizes-list">
                <span class="os-loading"><?php esc_html_e( 'Loading…', 'olama-stores' ); ?></span>
            </div>
        </div>
    </div>
</div>

<script>
(function($){
    // Tab switching
    $('.nav-tab').on('click', function(e){
        e.preventDefault();
        $('.nav-tab').removeClass('nav-tab-active');
        $(this).addClass('nav-tab-active');
        $('.os-tab-content').hide();
        $('#tab-'+$(this).data('tab')).show();
        if($(this).data('tab')==='warehouses') loadWarehouses();
        if($(this).data('tab')==='categories') loadCategories();
        if($(this).data('tab')==='units') loadUnits();
        if($(this).data('tab')==='providers') loadProviders();
        if($(this).data('tab')==='custom-models') loadCustomModels();
        if($(this).data('tab')==='fabrics') loadFabrics();
        if($(this).data('tab')==='colors') loadColors();
        if($(this).data('tab')==='sizes') loadSizes();
        if($(this).data('tab')==='entitlements') loadEntitlementsTab();
    });
    function loadWarehouses(){
        wp.apiFetch({ path:'/olama-stores/v1/warehouses' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th><?php esc_html_e("Location","olama-stores");?></th><th><?php esc_html_e("Type","olama-stores");?></th><th><?php esc_html_e("Status","olama-stores");?></th><th><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(w){ 
                var typeLabel = w.type.charAt(0).toUpperCase() + w.type.slice(1);
                html+='<tr><td>'+w.id+'</td><td>'+w.name+'</td><td>'+(w.location||'—')+'</td><td><span class="os-badge os-badge-'+w.type+'">'+typeLabel+'</span></td><td>'+(w.is_active?'Active':'Inactive')+'</td>'
                    + '<td><button type="button" class="button button-small os-edit-wh" data-id="'+w.id+'"><span class="dashicons dashicons-edit"></span></button></td></tr>'; 
            });
            $('#os-warehouses-list').html(html+'</tbody></table>');
        });
    }

    function loadCategories(){
        wp.apiFetch({ path:'/olama-stores/v1/categories' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th style="width: 100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(c){ 
                html+='<tr data-id="'+c.id+'"><td>'+c.id+'</td>'
                    + '<td><span class="view-mode">'+c.name+'</span><input type="text" class="edit-mode os-input" value="'+c.name+'" style="display:none; width: 100%;"></td>'
                    + '<td>'
                    + '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>'
                    + '</td></tr>'; 
            });
            $('#os-categories-list').html(html+'</tbody></table>');
        });
    }

    function loadUnits(){
        wp.apiFetch({ path:'/olama-stores/v1/units' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th><?php esc_html_e("Symbol","olama-stores");?></th><th style="width: 100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(u){ 
                html+='<tr data-id="'+u.id+'"><td>'+u.id+'</td>'
                    + '<td><span class="view-mode">'+u.name+'</span><input type="text" class="edit-mode-name os-input" value="'+u.name+'" style="display:none; width: 100%;"></td>'
                    + '<td><span class="view-mode">'+u.symbol+'</span><input type="text" class="edit-mode-symbol os-input" value="'+u.symbol+'" style="display:none; width: 100%;"></td>'
                    + '<td>'
                    + '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>'
                    + '</td></tr>'; 
            });
            $('#os-units-list').html(html+'</tbody></table>');
        });
    }

    function loadCustomModels(){
        wp.apiFetch({ path:'/olama-stores/v1/custom-models' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr>'
                + '<th>ID</th>'
                + '<th><?php esc_html_e("Name","olama-stores");?></th>'
                + '<th style="width:130px; text-align:center;"><?php esc_html_e("In Survey","olama-stores");?></th>'
                + '<th style="width:140px; text-align:center;"><?php esc_html_e("Calc Type","olama-stores");?></th>'
                + '<th style="width:120px;"><?php esc_html_e("Actions","olama-stores");?></th>'
                + '</tr></thead><tbody>';
            rows.forEach(function(m){
                var inSurvey = parseInt(m.include_in_survey) === 1;
                var calcType = (m.calculation_type === 'manual') ? 'manual' : 'auto';

                var surveyBadge = inSurvey
                    ? '<span class="os-survey-badge os-survey-yes"><span class="dashicons dashicons-yes-alt" style="font-size:14px;width:14px;height:14px;vertical-align:middle;"></span> <?php esc_html_e("Yes","olama-stores");?></span>'
                    : '<span class="os-survey-badge os-survey-no"><span class="dashicons dashicons-minus" style="font-size:14px;width:14px;height:14px;vertical-align:middle;"></span> <?php esc_html_e("No","olama-stores");?></span>';
                var surveyCheck = '<input type="checkbox" class="edit-mode-survey" style="display:none; margin:4px;" ' + (inSurvey ? 'checked' : '') + '>';

                var calcBadge = calcType === 'auto'
                    ? '<span style="display:inline-flex;align-items:center;gap:4px;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;background:#dbeafe;color:#1d4ed8;"><span class="dashicons dashicons-update" style="font-size:13px;width:13px;height:13px;"></span> <?php esc_html_e("Auto","olama-stores");?></span>'
                    : '<span style="display:inline-flex;align-items:center;gap:4px;padding:3px 10px;border-radius:12px;font-size:12px;font-weight:600;background:#fef3c7;color:#92400e;"><span class="dashicons dashicons-edit" style="font-size:13px;width:13px;height:13px;"></span> <?php esc_html_e("Manual","olama-stores");?></span>';
                var calcSelect = '<select class="edit-mode-calc-type" style="display:none;">'
                    + '<option value="auto"' + (calcType==='auto'?' selected':'') + '><?php esc_html_e("🤖 Auto","olama-stores");?></option>'
                    + '<option value="manual"' + (calcType==='manual'?' selected':'') + '><?php esc_html_e("✏️ Manual","olama-stores");?></option>'
                    + '</select>';

                html+=  '<tr data-id="'+m.id+'" data-survey="'+(inSurvey?1:0)+'" data-calc="'+calcType+'">';
                html += '<td>'+m.id+'</td>';
                html += '<td><span class="view-mode">'+m.name+'</span><input type="text" class="edit-mode-name os-input" value="'+m.name+'" style="display:none; width:100%;"></td>';
                html += '<td style="text-align:center;"><span class="view-mode survey-view">'+surveyBadge+'</span>'+surveyCheck+'</td>';
                html += '<td style="text-align:center;"><span class="view-mode calc-view">'+calcBadge+'</span>'+calcSelect+'</td>';
                html += '<td>';
                html += '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> ';
                html += '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> ';
                html += '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>';
                html += '</td></tr>';
            });
            $('#os-custom-models-list').html(html+'</tbody></table>');
        });
    }

    function loadFabrics(){
        wp.apiFetch({ path:'/olama-stores/v1/fabrics' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th style="width: 100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(f){ 
                html+='<tr data-id="'+f.id+'"><td>'+f.id+'</td>'
                    + '<td><span class="view-mode">'+f.name+'</span><input type="text" class="edit-mode-name os-input" value="'+f.name+'" style="display:none; width: 100%;"></td>'
                    + '<td>'
                    + '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>'
                    + '</td></tr>'; 
            });
            $('#os-fabrics-list').html(html+'</tbody></table>');
        });
    }

    function loadColors(){
        wp.apiFetch({ path:'/olama-stores/v1/colors' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th style="width: 100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(c){ 
                html+='<tr data-id="'+c.id+'"><td>'+c.id+'</td>'
                    + '<td><span class="view-mode">'+c.name+'</span><input type="text" class="edit-mode-name os-input" value="'+c.name+'" style="display:none; width: 100%;"></td>'
                    + '<td>'
                    + '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>'
                    + '</td></tr>'; 
            });
            $('#os-colors-list').html(html+'</tbody></table>');
        });
    }

    function loadSizes(){
        wp.apiFetch({ path:'/olama-stores/v1/sizes' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th>ID</th><th><?php esc_html_e("Name","olama-stores");?></th><th style="width: 100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(s){ 
                html+='<tr data-id="'+s.id+'"><td>'+s.id+'</td>'
                    + '<td><span class="view-mode">'+s.name+'</span><input type="text" class="edit-mode-name os-input" value="'+s.name+'" style="display:none; width: 100%;"></td>'
                    + '<td>'
                    + '<button type="button" class="button button-small os-edit-row"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small os-save-row" style="display:none;"><span class="dashicons dashicons-yes"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-row"><span class="dashicons dashicons-trash"></span></button>'
                    + '</td></tr>'; 
            });
            $('#os-sizes-list').html(html+'</tbody></table>');
        });
    }

    $('#os-btn-add-cat').on('click', function(){
        var name = $('#os-new-cat-name').val();
        if(!name) return;
        wp.apiFetch({ path:'/olama-stores/v1/categories', method:'POST', data:{ name: name } }).then(function(){
            $('#os-new-cat-name').val('');
            loadCategories();
        });
    });

    $('#os-btn-add-unit').on('click', function(){
        var name = $('#os-new-unit-name').val();
        var symbol = $('#os-new-unit-symbol').val();
        if(!name || !symbol) return;
        wp.apiFetch({ path:'/olama-stores/v1/units', method:'POST', data:{ name: name, symbol: symbol } }).then(function(){
            $('#os-new-unit-name').val(''); $('#os-new-unit-symbol').val('');
            loadUnits();
        });
    });

    $('#os-btn-add-model').on('click', function(){
        var name = $('#os-new-model-name').val();
        if(!name) return;
        wp.apiFetch({ path:'/olama-stores/v1/custom-models', method:'POST', data:{ name: name } }).then(function(){
            $('#os-new-model-name').val('');
            loadCustomModels();
        });
    });

    $('#os-btn-add-fabric').on('click', function(){
        var name = $('#os-new-fabric-name').val();
        if(!name) return;
        wp.apiFetch({ path:'/olama-stores/v1/fabrics', method:'POST', data:{ name: name } }).then(function(){
            $('#os-new-fabric-name').val('');
            loadFabrics();
        });
    });

    $('#os-btn-add-color').on('click', function(){
        var name = $('#os-new-color-name').val();
        if(!name) return;
        wp.apiFetch({ path:'/olama-stores/v1/colors', method:'POST', data:{ name: name } }).then(function(){
            $('#os-new-color-name').val('');
            loadColors();
        });
    });

    $('#os-btn-add-size').on('click', function(){
        var name = $('#os-new-size-name').val();
        if(!name) return;
        wp.apiFetch({ path:'/olama-stores/v1/sizes', method:'POST', data:{ name: name } }).then(function(){
            $('#os-new-size-name').val('');
            loadSizes();
        });
    });

    $(document).on('click', '.os-edit-row', function(){
        var row = $(this).closest('tr');
        row.find('.view-mode').hide();
        row.find('.edit-mode, .edit-mode-name, .edit-mode-symbol, .edit-mode-survey, .edit-mode-calc-type').show();
        $(this).hide();
        row.find('.os-save-row').show();
    });

    $(document).on('click', '.os-save-row', function(){
        var row = $(this).closest('tr');
        var id = row.data('id');
        var tab = row.closest('.os-tab-content').attr('id');
        var payload = {};

        if (tab === 'tab-categories') {
            payload.name = row.find('.edit-mode').val();
            wp.apiFetch({ path: '/olama-stores/v1/categories/' + id, method: 'PUT', data: payload }).then(function(){
                loadCategories();
            });
        } else if (tab === 'tab-custom-models') {
            payload.name = row.find('.edit-mode-name').val();
            payload.include_in_survey = row.find('.edit-mode-survey').is(':checked') ? 1 : 0;
            payload.calculation_type = row.find('.edit-mode-calc-type').val() || 'auto';
            wp.apiFetch({ path: '/olama-stores/v1/custom-models/' + id, method: 'PUT', data: payload }).then(function(){
                loadCustomModels();
            });
        } else if (tab === 'tab-fabrics') {
            payload.name = row.find('.edit-mode-name').val();
            wp.apiFetch({ path: '/olama-stores/v1/fabrics/' + id, method: 'PUT', data: payload }).then(function(){
                loadFabrics();
            });
        } else if (tab === 'tab-colors') {
            payload.name = row.find('.edit-mode-name').val();
            wp.apiFetch({ path: '/olama-stores/v1/colors/' + id, method: 'PUT', data: payload }).then(function(){
                loadColors();
            });
        } else if (tab === 'tab-sizes') {
            payload.name = row.find('.edit-mode-name').val();
            wp.apiFetch({ path: '/olama-stores/v1/sizes/' + id, method: 'PUT', data: payload }).then(function(){
                loadSizes();
            });
        } else {
            payload.name = row.find('.edit-mode-name').val();
            payload.symbol = row.find('.edit-mode-symbol').val();
            wp.apiFetch({ path: '/olama-stores/v1/units/' + id, method: 'PUT', data: payload }).then(function(){
                loadUnits();
            });
        }
    });

    $(document).on('click', '.os-delete-row', function(){
        if (!confirm('<?php esc_html_e("Are you sure you want to delete this?","olama-stores");?>')) return;
        var row = $(this).closest('tr');
        var id = row.data('id');
        var tab = row.closest('.os-tab-content').attr('id');
        var path = '';
        if (tab === 'tab-categories') path = '/olama-stores/v1/categories/';
        else if (tab === 'tab-custom-models') path = '/olama-stores/v1/custom-models/';
        else if (tab === 'tab-fabrics') path = '/olama-stores/v1/fabrics/';
        else if (tab === 'tab-colors') path = '/olama-stores/v1/colors/';
        else if (tab === 'tab-sizes') path = '/olama-stores/v1/sizes/';
        else path = '/olama-stores/v1/units/';

        wp.apiFetch({ path: path + id, method: 'DELETE' }).then(function(){
            if (tab === 'tab-categories') loadCategories(); 
            else if (tab === 'tab-custom-models') loadCustomModels();
            else if (tab === 'tab-fabrics') loadFabrics();
            else if (tab === 'tab-colors') loadColors();
            else if (tab === 'tab-sizes') loadSizes();
            else loadUnits();
        });
    });

    $(document).on('click', '.remove-row', function(){
        $(this).closest('.row').remove();
    });

    $('#os-btn-add-warehouse').on('click', function(){ 
        $('#os-wh-id').val('');
        $('#os-wh-modal-title').text('<?php esc_html_e("Add Warehouse","olama-stores");?>');
        $('#os-wh-name').val(''); $('#os-wh-name-ar').val(''); $('#os-wh-location').val(''); $('#os-wh-type').val('items');
        $('#os-warehouse-modal').show(); 
    });

    $(document).on('click', '.os-edit-wh', function(){
        var id = $(this).data('id');
        wp.apiFetch({ path:'/olama-stores/v1/warehouses' }).then(function(rows){
            var w = rows.find(function(x){ return x.id == id; });
            if(w){
                $('#os-wh-id').val(w.id);
                $('#os-wh-modal-title').text('<?php esc_html_e("Edit Warehouse","olama-stores");?>');
                $('#os-wh-name').val(w.name);
                $('#os-wh-name-ar').val(w.name_ar);
                $('#os-wh-location').val(w.location);
                $('#os-wh-type').val(w.type || 'items');
                $('#os-warehouse-modal').show();
            }
        });
    });

    $('#os-wh-save').on('click', function(){
        var id = $('#os-wh-id').val();
        var payload = {
            name: $('#os-wh-name').val(),
            name_ar: $('#os-wh-name-ar').val(),
            location: $('#os-wh-location').val(),
            type: $('#os-wh-type').val()
        };
        var method = id ? 'PUT' : 'POST';
        var path = id ? '/olama-stores/v1/warehouses/' + id : '/olama-stores/v1/warehouses';

        wp.apiFetch({ path: path, method: method, data: payload }).then(function(){ 
            $('#os-warehouse-modal').hide(); 
            loadWarehouses(); 
        }).catch(function(e){ alert(e.message); });
    });

    // Providers Logic
    function loadProviders(){
        wp.apiFetch({ path:'/olama-stores/v1/providers' }).then(function(rows){
            var html='<table class="wp-list-table widefat"><thead><tr><th><?php esc_html_e("Company","olama-stores");?></th><th><?php esc_html_e("Mobile","olama-stores");?></th><th><?php esc_html_e("Location","olama-stores");?></th><th><?php esc_html_e("Contact Person","olama-stores");?></th><th><?php esc_html_e("Status","olama-stores");?></th><th style="width:100px;"><?php esc_html_e("Actions","olama-stores");?></th></tr></thead><tbody>';
            rows.forEach(function(p){ 
                html+='<tr><td>'+p.company_name+'</td><td>'+(p.mobile_contact||'—')+'</td><td>'+(p.location||'—')+'</td><td>'+(p.contact_person||'—')+'</td>'
                    + '<td>'+(p.is_active == 1 ? '<strong>Active</strong>' : 'Inactive')+'</td>'
                    + '<td><button type="button" class="button button-small os-edit-provider" data-id="'+p.id+'"><span class="dashicons dashicons-edit"></span></button> '
                    + '<button type="button" class="button button-small button-link-delete os-delete-provider" data-id="'+p.id+'"><span class="dashicons dashicons-trash"></span></button></td></tr>'; 
            });
            $('#os-providers-list').html(html+'</tbody></table>');
        });
    }

    $('#os-btn-add-provider').on('click', function(){ 
        $('#os-provider-id').val('');
        $('#os-provider-modal-title').text('<?php esc_html_e("Add Provider","olama-stores");?>');
        $('#os-provider-name').val(''); $('#os-provider-mobile').val(''); $('#os-provider-location').val(''); $('#os-provider-person').val('');
        $('#os-provider-active').prop('checked', false);
        $('#os-provider-modal').show(); 
    });

    $(document).on('click', '.os-edit-provider', function(){
        var id = $(this).data('id');
        wp.apiFetch({ path: '/olama-stores/v1/providers' }).then(function(rows){
            var p = rows.find(function(x){ return x.id == id; });
            if(p){
                $('#os-provider-id').val(p.id);
                $('#os-provider-modal-title').text('<?php esc_html_e("Edit Provider","olama-stores");?>');
                $('#os-provider-name').val(p.company_name);
                $('#os-provider-mobile').val(p.mobile_contact);
                $('#os-provider-location').val(p.location);
                $('#os-provider-person').val(p.contact_person);
                $('#os-provider-active').prop('checked', p.is_active == 1);
                $('#os-provider-modal').show();
            }
        });
    });

    $('#os-provider-save').on('click', function(){
        var id = $('#os-provider-id').val();
        var payload = {
            company_name: $('#os-provider-name').val(),
            mobile_contact: $('#os-provider-mobile').val(),
            location: $('#os-provider-location').val(),
            contact_person: $('#os-provider-person').val(),
            is_active: $('#os-provider-active').is(':checked') ? 1 : 0
        };
        var method = id ? 'PUT' : 'POST';
        var path = id ? '/olama-stores/v1/providers/' + id : '/olama-stores/v1/providers';
        
        if (!payload.company_name) { alert('<?php esc_html_e("Company Name is required","olama-stores");?>'); return; }

        wp.apiFetch({ path: path, method: method, data: payload }).then(function(){
            $('#os-provider-modal').hide();
            loadProviders();
        }).catch(function(e){ 
            console.error('Provider Save Error:', e);
            alert(e.message || '<?php esc_html_e("Error saving provider","olama-stores");?>'); 
        });
    });

    $(document).on('click', '.os-delete-provider', function(){
        if(!confirm('<?php esc_html_e("Delete this provider?","olama-stores");?>')) return;
        wp.apiFetch({ path: '/olama-stores/v1/providers/' + $(this).data('id'), method: 'DELETE' }).then(function(){
            loadProviders();
        }).catch(function(e){ alert(e.message); });
    });

    // Reset Store Data for Testing
    $('#os-btn-reset-store-data').on('click', function(e){
        e.preventDefault();
        
        var confirm1 = confirm('<?php echo esc_js( __("WARNING: You are about to DELETE all transactions (movements, assignments, transfers, inventory counts) and zero all stock balances. This action is irreversible. Are you sure you want to proceed?", "olama-stores") ); ?>');
        if (!confirm1) {
            return;
        }
        
        var confirm2 = confirm('<?php echo esc_js( __("FINAL WARNING: Are you absolutely sure? Click OK to execute data reset.", "olama-stores") ); ?>');
        if (!confirm2) {
            return;
        }

        var btn = $(this);
        btn.prop('disabled', true).text('<?php echo esc_js( __("Resetting store data...", "olama-stores") ); ?>').css('background', '#777');

        wp.apiFetch({
            path: '/olama-stores/v1/stock/reset-testing',
            method: 'POST'
        }).then(function(response) {
            alert('<?php echo esc_js( __("Store data has been successfully reset. All transactions are deleted, and stock levels are set to zero.", "olama-stores") ); ?>');
            location.reload();
        }).catch(function(error) {
            alert('<?php echo esc_js( __("Error resetting store data: ", "olama-stores") ); ?>' + error.message);
            btn.prop('disabled', false).text('<?php echo esc_js( __("Delete All Transactions & Zero Balances", "olama-stores") ); ?>').css('background', '#d63638');
        });
    });

    // Clear Warehouse
    $('#os-btn-clear-warehouse').on('click', function(e){
        e.preventDefault();
        
        var confirm1 = confirm('<?php echo esc_js( __("WARNING: You are about to permanently delete all transactions (movements, custody assignments, returns, transfers, and inventory counts) from the store. This action cannot be undone. Are you sure you want to proceed?", "olama-stores") ); ?>');
        if (!confirm1) {
            return;
        }
        
        var confirm2 = confirm('<?php echo esc_js( __("FINAL WARNING: Are you absolutely sure you want to clear all transactions and zero out stock levels? (Setting details and items list will be kept).", "olama-stores") ); ?>');
        if (!confirm2) {
            return;
        }

        var btn = $(this);
        btn.prop('disabled', true).text('<?php echo esc_js( __("Clearing warehouse...", "olama-stores") ); ?>').css('background', '#777');

        wp.apiFetch({
            path: '/olama-stores/v1/stock/reset-testing',
            method: 'POST'
        }).then(function(response) {
            alert('<?php echo esc_js( __("Olama store transactions have been successfully cleared. Settings and the items list are kept, and stock levels are set to zero.", "olama-stores") ); ?>');
            location.reload();
        }).catch(function(error) {
            alert('<?php echo esc_js( __("Error clearing warehouse: ", "olama-stores") ); ?>' + error.message);
            btn.prop('disabled', false).text('<?php echo esc_js( __("Clear Warehouse", "olama-stores") ); ?>').css('background', 'var(--os-danger)');
        });
    });

    // Close modals
    $('.os-modal-close, .os-modal').on('click', function(e){
        if(e.target===this || $(e.target).hasClass('os-modal-close')) $(this).closest('.os-modal').hide();
    });
    // REC-14: Year-End Transition
    $('#os-yt-load-summary').on('click', function(){
        var $wrap = $('#os-year-transition-summary');
        $wrap.html('<span class="os-loading"><?php esc_html_e("Loading…","olama-stores");?></span>');
        wp.apiFetch({ path: '/olama-stores/v1/reports/year-transition/summary' }).then(function(d){
            $wrap.html(
                '<div style="display:grid; grid-template-columns:repeat(4,1fr); gap:12px;">'
                + '<div style="text-align:center; background:#fff; border-radius:6px; padding:12px;"><div style="font-size:1.8em; font-weight:700; color:#0073aa;">'+d.open_custody+'</div><div style="font-size:.8em; color:#666;"><?php esc_html_e("Open Employee Custody","olama-stores");?></div></div>'
                + '<div style="text-align:center; background:#fff; border-radius:6px; padding:12px;"><div style="font-size:1.8em; font-weight:700; color:#22c55e;">'+d.open_student+'</div><div style="font-size:.8em; color:#666;"><?php esc_html_e("Open Student Issues","olama-stores");?></div></div>'
                + '<div style="text-align:center; background:#fff; border-radius:6px; padding:12px;"><div style="font-size:1.8em; font-weight:700; color:#d63638;">'+d.overdue_custody+'</div><div style="font-size:.8em; color:#666;"><?php esc_html_e("Overdue Returns","olama-stores");?></div></div>'
                + '<div style="text-align:center; background:#fff; border-radius:6px; padding:12px;"><div style="font-size:1.4em; font-weight:700; color:#7c3aed;">'+parseFloat(d.total_stock_value||0).toLocaleString(undefined,{maximumFractionDigits:0})+'</div><div style="font-size:.8em; color:#666;"><?php esc_html_e("Stock Value","olama-stores");?></div></div>'
                + '</div>'
                + '<p style="margin-top:12px; font-size:.85em; color:#666;"><?php esc_html_e("Active Year:","olama-stores");?> <strong>' + d.year_name + '</strong></p>'
            );
        }).catch(function(e){ $wrap.html('<p class="os-error">' + (e.message||'Error') + '</p>'); });
    });

    $('#os-yt-export-balances').on('click', function(){
        if(!confirm('<?php esc_html_e("Export current stock balances to Excel before year transition?","olama-stores");?>')) return;
        window.location = olamaStores.apiRoot + '/reports/export/stock?_wpnonce=' + olamaStores.nonce;
    });

    $('#os-yt-flag-overdue').on('click', function(){
        if(!confirm('<?php esc_html_e("Flag all overdue custody records with a year-end note? This updates their notes field only.","olama-stores");?>')) return;
        var $btn = $(this).prop('disabled', true);
        wp.apiFetch({ path:'/olama-stores/v1/reports/year-transition/run', method:'POST', data:{ action:'flag_overdue_custody' } })
            .then(function(r){ alert('<?php esc_html_e("Flagged","olama-stores");?> ' + r.flagged + ' <?php esc_html_e("overdue records.","olama-stores");?>'); })
            .catch(function(e){ alert(e.message||'Error'); })
            .finally(function(){ $btn.prop('disabled',false); });
    });

    // ── Uniform Entitlements JS ──
    function loadEntitlementsTab() {
        Promise.all([
            wp.apiFetch({ path: '/olama-stores/v1/grades' }),
            wp.apiFetch({ path: '/olama-stores/v1/custom-models' }),
            wp.apiFetch({ path: '/olama-stores/v1/entitlements?academic_year_id=' + olamaStores.activeYearId })
        ]).then(function(results){
            var grades = results[0];
            var models = results[1];
            var entitlements = results[2];

            // Populate grade dropdown
            var gradeHtml = '<option value=""><?php esc_html_e("Select Grade…", "olama-stores"); ?></option>';
            grades.forEach(function(g){ gradeHtml += '<option value="'+g.id+'">'+g.grade_name+'</option>'; });
            $('#os-ent-grade').html(gradeHtml);

            // Populate model dropdown
            var modelHtml = '<option value=""><?php esc_html_e("Select Model…", "olama-stores"); ?></option>';
            models.forEach(function(m){ modelHtml += '<option value="'+m.id+'">'+m.name+'</option>'; });
            $('#os-ent-model').html(modelHtml);

            renderEntitlementsList(entitlements);
        }).catch(function(e) {
            $('#os-entitlements-list').html('<p class="os-error">' + (e.message || 'Error loading metadata.') + '</p>');
        });
    }

    function renderEntitlementsList(list) {
        if (!list || !list.length) {
            $('#os-entitlements-list').html('<p><?php esc_html_e("No entitlements defined for the active year.", "olama-stores"); ?></p>');
            return;
        }

        var html = '<table class="wp-list-table widefat striped">'
            + '<thead><tr>'
            + '<th><?php esc_html_e("Grade", "olama-stores"); ?></th>'
            + '<th><?php esc_html_e("Uniform Model", "olama-stores"); ?></th>'
            + '<th style="text-align:center;"><?php esc_html_e("Quantity", "olama-stores"); ?></th>'
            + '<th style="width: 100px;"><?php esc_html_e("Actions", "olama-stores"); ?></th>'
            + '</tr></thead><tbody>';

        list.forEach(function(e) {
            html += '<tr>'
                + '<td>' + (e.grade_name || 'Grade #' + e.grade_id) + '</td>'
                + '<td>' + (e.model_name || 'Model #' + e.custom_model_id) + '</td>'
                + '<td style="text-align:center;">' + e.quantity + '</td>'
                + '<td><button type="button" class="button button-small button-link-delete os-delete-entitlement" data-id="' + e.id + '"><span class="dashicons dashicons-trash"></span></button></td>'
                + '</tr>';
        });

        html += '</tbody></table>';
        $('#os-entitlements-list').html(html);
    }

    $('#os-btn-add-entitlement').on('click', function() {
        var gradeId = $('#os-ent-grade').val();
        var modelId = $('#os-ent-model').val();
        var qty = $('#os-ent-qty').val();

        if (!gradeId || !modelId || !qty || qty <= 0) {
            alert('<?php esc_html_e("Please fill in grade, model, and quantity.", "olama-stores"); ?>');
            return;
        }

        var payload = {
            academic_year_id: olamaStores.activeYearId,
            grade_id: parseInt(gradeId),
            custom_model_id: parseInt(modelId),
            quantity: parseInt(qty)
        };

        var $btn = $(this);
        $btn.prop('disabled', true).text('<?php esc_html_e("Adding…", "olama-stores"); ?>');
        
        wp.apiFetch({
            path: '/olama-stores/v1/entitlements',
            method: 'POST',
            data: payload
        }).then(function() {
            $('#os-ent-qty').val(1);
            $('#os-ent-grade').val('');
            $('#os-ent-model').val('');
            // Reload list
            wp.apiFetch({ path: '/olama-stores/v1/entitlements?academic_year_id=' + olamaStores.activeYearId }).then(function(entitlements){
                renderEntitlementsList(entitlements);
            });
        }).catch(function(err) {
            alert(err.message || 'Error saving entitlement');
        }).finally(function() {
            $btn.prop('disabled', false).text('<?php esc_html_e("Add Entitlement", "olama-stores"); ?>');
        });
    });

    $(document).on('click', '.os-delete-entitlement', function() {
        if (!confirm('<?php esc_html_e("Delete this entitlement rule?", "olama-stores"); ?>')) return;
        var id = $(this).data('id');
        var $row = $(this).closest('tr').css('opacity', 0.5);
        
        wp.apiFetch({
            path: '/olama-stores/v1/entitlements/' + id,
            method: 'DELETE'
        }).then(function() {
            wp.apiFetch({ path: '/olama-stores/v1/entitlements?academic_year_id=' + olamaStores.activeYearId }).then(function(entitlements){
                renderEntitlementsList(entitlements);
            });
        }).catch(function(err) {
            $row.css('opacity', 1);
            alert(err.message || 'Error deleting entitlement');
        });
    });

})(jQuery);
</script>
<style>
.os-survey-badge {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 600;
    line-height: 1.5;
}
.os-survey-yes {
    background: #dcfce7;
    color: #16a34a;
    border: 1px solid #bbf7d0;
}
.os-survey-no {
    background: #f3f4f6;
    color: #6b7280;
    border: 1px solid #e5e7eb;
}
</style>

